### PR TITLE
Support for graphene 3.0.0b7

### PR DESCRIPTION
**Pull request by Koldar**
Hi, I needed to add support for graphene 3.0.0b7, since my project uses it and I cannot downgrade to 2.1.1.

Some notes:

1. some functions were rpesent in grpahene 2 but not in graphene 3. For every function missing I have created in the new file called `graphql_compatibility.py` a generic function that perform the function task both in graphene 2 and in graphene 3;
2. auto_camelcase seems not be stored in any graphene 3 datastructure. To support it, I have manually added in the `build_schema` called by graphene-foundation;
3. for unit testing: it seems that between graphene 2 and graphene 3 the order of the types generated in the generated schemas is different (as well as some input that are marked as nullable). I think the schema changes are not significant, but just to be sure in the unit testing I created some switch that check the actual and the expected schemas dependning on the graphene version: the tests are now a bit verbose, but they should be backward compatible;
4. With all this said, unit testing is all green;
5.  integration-tests: sadly I am really a noob with docker, hence I had a lot of troubles of making the integration tests work. I created a new version of each docker service called "3" (for graphene 3). First flask-graphql insisted on not working (it still points to 2.1.1, AFAIK); So i decided to switch every `service_3` implementation to django. I changed the ports just for safety and updated apollo dependencies (in `federation_3`) to the latest ones: even so, `federation_3` service still does not start correctly (container unhealty) due to the fact that `federation_3` fails to connect to service_3_a. I really don't know how to solve such an issue: **any idea about it?**;
6. I have updated the `Makefile` with convenient (at least for me) target, but please feel free to ignore those changes

What do you think? Do you have any notes about this merge? Thanks

### CODE REVIEW

**Comment by fabianriewe** [comment]
Any news on this PR?

**Comment by Koldar** [comment]
I have been using the merged pull request with no problems (tests do not work though). It should be safe to use

**Comment by fabianriewe** [comment]
Same on my end. @tcleonard can you merge this?

**Comment by tcleonard** [comment]
Thanks a lot for this MR and sorry for the late reply. 
I have created an updated version (https://github.com/loft-orbital/graphene-federation/pull/4) which is compatible with v3.1.0 of graphene (but drops the support for v2 to clean up the code) and cleans up various things. 
So I am closing this MR as it is kind of a duplicate.

**Pull request closed without merging**
